services:
    apidemo:
        build: apidemo
        mem_limit: 512m
        ports:
         - "8080:8080"
        environment:
         DB_URL: jdbc:mysql://my_database:3306/spring?createDatabaseIfNotExist=true
         DB_USER_NAME: ${USER_NAME}
         DB_PASSWORD: ${PASSWORD}
        restart: always
        depends_on:
         my_database:
            condition: service_healthy
    my_database:
        image: mysql
        ports:
         - "3307:3306"
        environment:
         MYSQL_ROOT_PASSWORD: ${PASSWORD}
         MYSQL_PASSWORD: ${PASSWORD}
         MYSQL_DATABASE: spring
        restart: always
        healthcheck:
         test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
         timeout: 10s
         retries: 10
        volumes:
         - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
            
